### PR TITLE
Add integration test project

### PR DESCRIPTION
**Pull request by ewilde**
This addresses #15 

*TODO*

- [ ] Add utility commands to start and stop a syslog server
- [ ] Write happy path test, which sends a message to the syslog server
- [ ] Write the connection down test. 
 * Send a log line whilst the server is up
 * Take the server down
 * Retry logic should kick-in
 * Bring syslog server backup
 * Sending of logs should resume

### CODE REVIEW

**Comment by mrdavidlaing** [comment]
FWIW, nxlog can act as a sylog receiver; and can be configured to route received messages to a file.  

I even started (but never finished) something related to this over on the LSS project - https://github.com/cityindex/LogSearchShipper/blob/master/src/IntegrationTests/MultilineTests.cs#L25

**Comment by ewilde** [comment]
@mrdavidlaing great was having fun writing my own syslog

**Comment by fandrei** [comment]
@ewilde, @mrdavidlaing, I've extended these tests and added a case when the server doesn't respond to the connection attempts; I found and fixed a race condition in my appender's code.

There is another problem I discovered; it makes the appender lose a few log messages if the connection breaks (and then gets reconnected). Here is an isolated test to reproduce such a case: https://github.com/fandrei/TcpClientTest2/blob/master/TcpClientTest2/Program.cs

Basically, it's doing the following:
1. Establish a client-server TLS connection
2. Interrupt this connection from the server side
3. The client writes some data to the connection, and this code returns "sending success" status despite none data were actually sent to the server, as the connection was already closed before this attempt
As far as I understand it's a featurebug of TCP/IP http://blog.netherlabs.nl/articles/2009/01/18/the-ultimate-so_linger-page-or-why-is-my-tcp-not-reliable, and the higher level protocol (i.e, RFC 5424) should have means to track how many log messages were actually delivered to the server; but it seems it doesn't.
So far I don't see any solutions to this problem.

**Comment by fandrei** [comment]
The answer I've got from one of syslog-over-TCP RFC authors:

```
Yes, you are absolutely right, but that's the way it simply is.
Traditional syslog does not provide this capability and the new
RFC5424 based series unfortunately also does not have a transport
mapping that does. There was inssufficient willingness to adapt
rfc3080 to the new series in the working group when we defined this.
And many folks have insisted that we keep the traditional semantics.

This resulted in the creation of the non-standard RELP protocol [1]
for my use in rsyslog.

The traditional approach, however, is to either ignore this problem or
re-send a (sometimes configurable) number of messages, accepting
potential duplication.

Sorry I do not have a better answer. Still hope it helps,
Rainer

[1] http://blog.gerhards.net/2008/03/relp-reliable-event-logging-protocol.html
```

**Pull request merged**
